// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC7LeammhZEguj_j4qLeULtqPyy5DY7NCs',
    appId: '1:758236903398:web:4c8c8caf53adf438ec8827',
    messagingSenderId: '758236903398',
    projectId: 'sudoku-96650',
    authDomain: 'sudoku-96650.firebaseapp.com',
    databaseURL: 'https://sudoku-96650-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'sudoku-96650.firebasestorage.app',
    measurementId: 'G-WR9K96L8GE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA6i5MSz6yIGRK7ZP1lbZ3Q7cobxvnWOlU',
    appId: '1:758236903398:android:19f4b2a49203d7d5ec8827',
    messagingSenderId: '758236903398',
    projectId: 'sudoku-96650',
    databaseURL: 'https://sudoku-96650-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'sudoku-96650.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCOA6NrAVaZcbT29MGmwhkhdTyzTG5-1DA',
    appId: '1:758236903398:ios:7fc739391a8c4d5cec8827',
    messagingSenderId: '758236903398',
    projectId: 'sudoku-96650',
    databaseURL: 'https://sudoku-96650-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'sudoku-96650.firebasestorage.app',
    iosBundleId: 'com.rocketgamestation.sudoku',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCOA6NrAVaZcbT29MGmwhkhdTyzTG5-1DA',
    appId: '1:758236903398:ios:7fc739391a8c4d5cec8827',
    messagingSenderId: '758236903398',
    projectId: 'sudoku-96650',
    databaseURL: 'https://sudoku-96650-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'sudoku-96650.firebasestorage.app',
    iosBundleId: 'com.rocketgamestation.sudoku',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC7LeammhZEguj_j4qLeULtqPyy5DY7NCs',
    appId: '1:758236903398:web:69aecd637211b1c6ec8827',
    messagingSenderId: '758236903398',
    projectId: 'sudoku-96650',
    authDomain: 'sudoku-96650.firebaseapp.com',
    databaseURL: 'https://sudoku-96650-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'sudoku-96650.firebasestorage.app',
    measurementId: 'G-9JCQBJ5JLG',
  );
}
