// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDtYJYOIJhE-vUIynepsolPZPonYyTVpXM',
    appId: '1:712783270069:web:9720a97db621007e4faefc',
    messagingSenderId: '712783270069',
    projectId: 'sudoku-challenge-98e4d',
    authDomain: 'sudoku-challenge-98e4d.firebaseapp.com',
    databaseURL: 'https://sudoku-challenge-98e4d-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'sudoku-challenge-98e4d.firebasestorage.app',
    measurementId: 'G-N6C1QG9VB4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA2yelewNOYCo7hAICfrHAbYCZTckgIN6g',
    appId: '1:712783270069:android:1739a3d425201a784faefc',
    messagingSenderId: '712783270069',
    projectId: 'sudoku-challenge-98e4d',
    databaseURL: 'https://sudoku-challenge-98e4d-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'sudoku-challenge-98e4d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAYyzQdUZJfcIjElRAshirDSDHapxZ4em8',
    appId: '1:712783270069:ios:364877b45542e4a24faefc',
    messagingSenderId: '712783270069',
    projectId: 'sudoku-challenge-98e4d',
    databaseURL: 'https://sudoku-challenge-98e4d-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'sudoku-challenge-98e4d.firebasestorage.app',
    iosBundleId: 'com.example.sudoku',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAYyzQdUZJfcIjElRAshirDSDHapxZ4em8',
    appId: '1:712783270069:ios:364877b45542e4a24faefc',
    messagingSenderId: '712783270069',
    projectId: 'sudoku-challenge-98e4d',
    databaseURL: 'https://sudoku-challenge-98e4d-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'sudoku-challenge-98e4d.firebasestorage.app',
    iosBundleId: 'com.example.sudoku',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDtYJYOIJhE-vUIynepsolPZPonYyTVpXM',
    appId: '1:712783270069:web:4f80c3d299f6fbb74faefc',
    messagingSenderId: '712783270069',
    projectId: 'sudoku-challenge-98e4d',
    authDomain: 'sudoku-challenge-98e4d.firebaseapp.com',
    databaseURL: 'https://sudoku-challenge-98e4d-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'sudoku-challenge-98e4d.firebasestorage.app',
    measurementId: 'G-B7LPMFTB0Z',
  );
}
